name: quicksave_app
description: "1 Click Video Download - Download video e audio da qualsiasi sito"
publish_to: 'none'
version: 1.1.1+3

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.0.0
  dio: ^5.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  provider: ^6.1.1
  share_plus: ^7.2.1
  open_filex: ^4.3.4
  google_mobile_ads: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
